name: Test

on: [push]


env:
  cache-version: v1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements/install.txt  -r requirements/test.txt

      - name: Install this package.
        run: |
          pip install -e .

      - name: test
        run: |
          nosetests -v
